repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort - Imports sorter
        exclude: migrations
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black - Code formatter
        exclude: migrations

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 - Style consistency (linter)
        exclude: migrations

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit - Security issues detector

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.277"
    hooks:
      - id: ruff
        name: ruff - A collection of cool stuff :)
        exclude: migrations

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle - Docstring style checker
        exclude: migrations
        args:
          - --convention=google
          - --add-ignore=D100,D101,D104,D105,D106,D107,D202,D203,D213
