version: '3.6'

services:
  database:
    container_name: alfawal-uav-project-postgres
    image: postgres
    user: postgres
    env_file: ../.env
    # No need to expose the port unless you want to access it from
    # outside the Docker network
    # ports:
    #   - "5432:5432"
  django:
    container_name: alfawal-uav-project-django
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 90s
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
